# Change these first
owner: cake-tech # Your GitHub organization or username, where this repository lives
repo: upptime-monerocom # The name of this repository

sites:
  - name: xmr-node.cakewallet.com:18081
    check: "tcp-ping"
    url: xmr-node.cakewallet.com
    port: 18081
    icon: https://cakewallet.com/assets/images/logo/Cake%20Wallet%20Logo%202021_App%20Icon.png
  - name: node.sethforprivacy.com:18089
    check: "tcp-ping"
    url: node.sethforprivacy.com
    port: 18089
  - name: nodes.hashvault.pro:18081
    check: "tcp-ping"
    url: nodes.hashvault.pro
    port: 18081
  - name: node.c3pool.com:18081
    check: "tcp-ping"
    url: node.c3pool.com
    port: 18081
  - name: node.supportxmr.com:18081
    check: "tcp-ping"
    url: node.supportxmr.com
    port: 18081
  - name: node.community.rino.io:18081
    check: "tcp-ping"
    url: node.community.rino.io
    port: 18081
  - name: node.moneroworld.com:18089
    check: "tcp-ping"
    url: node.moneroworld.com
    port: 18089

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: nodes.monero.com
  # baseUrl: /upptime-cakewallet
  logoUrl: https://i.imgur.com/WxsaoFP.png
  favicon: https://i.imgur.com/b4SMfd6.png
  name: Monero.com Nodes
  introTitle: "Monero Nodes Status by Cake Wallet"
  introMessage: Monero node status is updated approximately every 5-30 minutes. Charts are updated less frequently. Unless specified, these nodes are run by other parties who may log your traffic. Use your own node if possible for maximum privacy. For the official website of The Monero Project, go to getmonero.org.
  theme: light
  navbar:
    - title: Twitter
      href: https://twitter.com/MoneroCom
    - title: Email Support
      href: mailto:support@cakewallet.com
    - title: Telegram Support
      href: https://t.me/cakewallet_bot

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
